name: Build Argus IPA

on:
  workflow_dispatch:

jobs:
  build:
    name: Mac Üzerinde Derle
    runs-on: macos-14

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4
        with:
          ref: 'ui/v5-designkit' # İŞTE SİHİRLİ SATIR BURASI! Çalışan dalı seçiyoruz.

      - name: Xcode Sürümünü Ayarla
        run: |
          XCODE_PATH=$(ls -d /Applications/Xcode_16*.app | head -n 1)
          sudo xcode-select -s "$XCODE_PATH/Contents/Developer"
          xcodebuild -version

      - name: Gerekli Konfigürasyon Dosyasını Oluştur
        run: cp Secrets.xcconfig.example Secrets.xcconfig

      - name: Uygulamayı Derle (İmzasız)
        run: |
          xcodebuild clean build \
            -project argus.xcodeproj \
            -scheme argus \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: IPA Formatına Çevir
        run: |
          mkdir Payload
          mv build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r Argus.ipa Payload

      - name: Çıktıyı Kullanıcıya Sun
        uses: actions/upload-artifact@v4
        with:
          name: Argus-IPA-Dosyasi
          path: Argus.ipa
